// list of tasks to complete
const tasksNormal = {
    1 : {type:'mat', startMat: [1,0,0,1], endMat: [1,0,0,1], startVec: {'x':1,'y':1}, endVec: {'x':5,'y':5}, 
        description: 'Can you scale the vector to match? ',
        endCard: 'Congratualations! Well done on completing the first task'},
    2 : {type:'mat', startMat: [1,0,0,1], endMat: [1,0,0,1], startVec: {'x':1,'y':1}, endVec: {'x':1,'y':5}, 
        description: 'Can you move the y-axis?',
        endCard: 'You scaled just one of the axis!'},
    3 : {type:'mat', startMat: [1,0,0,1], endMat: [1,0,0,1], startVec: {'x':1,'y':5}, endVec: {'x':-5,'y':1}, 
        description: 'Can you move the x-axis?',
        endCard: 'Well done!'},
    4 : {type:'mat', startMat: [1,0,0,1], endMat: [1,0,0,1], startVec: {'x':1,'y':1}, endVec: {'x':-4,'y':-3}, 
        description: 'How about both at once?',
        endCard: 'Can you see how this can be extended to move to any point on the plane?'},
    5 : {type:'vec', startMat: [1,0,0,1], endMat: [-1,0,0,-1], startVec: {'x':5,'y':5}, endVec: {'x':5,'y':5}, 
        description: 'Can you act against the transformation?',
        endCard: 'You can flip the vector!'},
    6 : {type:'vec', startMat: [1,0,0,1], endMat: [1,2,2,1], startVec: {'x':1,'y':1}, endVec: {'x':1,'y':1},
        description: 'Try and get the vectors to match',
        endCard: 'Notice anything about the two vectors?'},
    7 : {type:'vec', startMat: [1,0,0,1], endMat: [1,2,2,1], startVec: {'x':-1,'y':1}, endVec: {'x':-1,'y':1},
        description: 'Try and see the link between the two vectors you are using',
        endCard: 'Seen a link?'},
    8 : {type:'vec', startMat: [1,3,4,2], endMat: [1,0,0,1], startVec: {'x':1,'y':1}, endVec: {'x':-15,'y':-20},
        description: 'Again think about what links the two vectors',
        endCard: 'Consider how they have changed'},
    9 : {type:'vec', startMat: [1,0,0,1], endMat: [3,2,2,3], startVec: {'x':1,'y':1}, endVec: {'x':1,'y':1},
        description: 'Try and see the link between the two vectors you are using',
        endCard: 'Seen a link?'},
    10 : {type:'vec', startMat: [1,2,2,1], endMat: [3,2,2,3], startVec: {'x':1,'y':1}, endVec: {'x':-1,'y':1},
        description: 'Some fun extra tasks now you have completed the main ones',
        endCard: 'Well done!'},
    11 : {type:'mat', startMat: [1,0,0,1], endMat: [1,2,2,1], startVec: {'x':1,'y':1}, endVec: {'x':-1,'y':1},
        description: 'Can you match the vectors even with a matrix applied to the output?',
        endCard: 'Can you see the link in reverse?'},
    12 : {type:'mat', startMat: [1,0,0,1], endMat: [1,2,2,1], startVec: {'x':1,'y':1}, endVec: {'x':3,'y':3},
        description: 'Can you match the vectors even with a matrix applied to the output?',
        endCard: 'Seen a link?'},
}

// inverse tasks to be implemented
const inverseTasks = {
    1 : {type:'inverse', startMat: [1,0,0,1], endMat: [5,0,0,5], 
        description: 'Can you match these matrices? ',
        endCard: 'Congratualations! Well done on completing the first task'},
    2 : {type:'inverse', startMat: [1,2,2,1], endMat: [2,1,1,2], 
        description: 'How about this one?',
        endCard: ''},
    3 : {type:'inverse', startMat: [5,0,0,5], endMat: [1,0,0,1], 
        description: 'Is there anything connecting these two?',
        endCard: 'Congratualations! You have inverted a matrix!'},
    4 : {type:'inverse', startMat: [-4,0,0,4], endMat: [1,0,0,1], 
        description: 'Here we have a reflection as well as a scale',
        endCard: 'Well done!'},
    5 : {type:'inverse', startMat: [1,0,1,1], endMat: [1,0,0,1],
        description: 'Here the y-axis has rotated',
        endCard: 'Notice the relation between the two matrices?'},
    6 : {type:'inverse', startMat: [1,2,0,1], endMat: [1,0,0,1],
        description: 'Here the x-axis has rotated',
        endCard: 'Notice the relation between the two matrices?'},
    7 : {type:'inverse', startMat: [1,2,0,1], endMat: [-1,0,0,-1],
        description: 'here the y-axis has rotated',
        endCard: 'Notice the relation between the two matrices?'},
    8 : {type:'inverse', startMat: [1,2,2,1], endMat: [3,0,0,3],
        description: 'here the y-axis has rotated',
        endCard: 'Notice the relation between the two matrices?'},
    9 : {type:'inverse', startMat: [1,0,1,1], endMat: [1,0,0,1],
        description: 'here the y-axis has rotated',
        endCard: 'Notice the relation between the two matrices?'},
}

export {tasksNormal, inverseTasks}